import HomePage from '@/components/Feature/HomePage'
import Head from 'next/head'
import { Fragment } from 'react'

const Home = () => (
  <Fragment>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HomePage />
  </Fragment>
)

export default Home
